# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "ubuntu/trusty64"
#	config.vm.box = "mreil/ubuntu-trusty-mini"

	config.vm.network :private_network, ip:"192.168.33.10"
	config.vm.hostname = "localhost"

#	config.vm.network :forwarded_port, guest: 80, host: 10080 # http

	config.vm.synced_folder "../../src", "/var/src", :create => true, :owner => 'vagrant', :group => 'vagrant', :mount_options => ['dmode=777', 'fmode=666']

	unless Vagrant.has_plugin?('vagrant-omnibus')
		system('vagrant plugin install vagrant-omnibus') || exit!
		exit system('vagrant', *ARGV)
	end

	config.omnibus.chef_version = :latest

	config.ssh.forward_x11 = true

	config.vm.provision "chef_solo" do |chef|
		chef.cookbooks_path = "../../chef/site-cookbooks/"
		chef.environments_path = "../../chef/environments/"
		chef.environment = "vagrant"
		chef.run_list = %w[
			recipe[linux::localedef_for_UTF-8]
		]
	end

end
