# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "Env01"
	config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"

	config.vm.network :private_network, ip:"192.168.33.10"
	config.vm.hostname = "localhost"

	config.vm.network :forwarded_port, guest: 80, host: 10080 # http
	config.vm.network :forwarded_port, guest: 8080, host: 18080 # http
	config.vm.network :forwarded_port, guest: 3000, host: 3000 # node.js
	config.vm.network :forwarded_port, guest: 3001, host: 3001 # node.js
	config.vm.network :forwarded_port, guest: 3002, host: 3002 # node.js

	config.vm.synced_folder "../../src/node.js_sample_03", "/var/www/src", :create => true, :owner => 'vagrant', :group => 'vagrant', :mount_options => ['dmode=777', 'fmode=666']

	config.vm.provision "chef_solo" do |chef|
		chef.cookbooks_path = "../../chef/site-cookbooks/"
		chef.environments_path = "../../chef/environments/"
		chef.environment = "vagrant"
		chef.run_list = %w[
			recipe[linux::localedef_for_UTF-8]
			recipe[linux::sudoers_for_path]
			recipe[security-updates::bash-shellshock]
			recipe[redis::install_redis_for_centos]
			recipe[node.js]
			recipe[node.js::express]
			recipe[node.js::pm2]
		]
	end

	config.omnibus.chef_version = :latest

	config.ssh.forward_x11 = true

end
