# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "CentOS_6.5.3_Minimal"
	config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"
#	config.vm.box_url = "bento/centos-7.1"

	config.vm.network :private_network, ip:"192.168.33.10"
	config.vm.hostname = "localhost"

	config.vm.network :forwarded_port, guest: 80, host: 10080 # http
	config.vm.network :forwarded_port, guest: 8080, host: 18080 # http
	config.vm.network :forwarded_port, guest: 8082, host: 18082 # http
	config.vm.network :forwarded_port, guest: 8180, host: 18180 # jenkins
	config.vm.network :forwarded_port, guest: 3000, host: 3000 # rails
	config.vm.network :forwarded_port, guest: 3690, host: 3690 # subversion

	config.vm.synced_folder "../../src", "/var/www/src", :create => true, :owner => 'vagrant', :group => 'vagrant', :mount_options => ['dmode=777', 'fmode=666']

	config.vm.provision "chef_solo" do |chef|
		chef.cookbooks_path = "../../chef/site-cookbooks/"
		chef.environments_path = "../../chef/environments/"
		chef.environment = "vagrant"
		chef.run_list = %w[
			recipe[linux::localedef_for_UTF-8]
			recipe[linux::sudoers_for_path]
			recipe[security-updates::bash-shellshock]
			recipe[elixir]
			recipe[elixir::phoenix]
		]
	end

	config.omnibus.chef_version = :latest

	config.ssh.forward_x11 = true

end
